sonar.projectKey=MarketSafe-4350_MarketSafe
sonar.organization=marketsafe-4350

sonar.sources=server
sonar.exclusions=**/tests/**,frontend/**
sonar.coverage.exclusions=**/tests/**,frontend/**
sonar.python.coverage.reportPaths=server/coverage.xml
sonar.sourceEncoding=UTF-8