[cosmic-ray]
module-path = [
    "src/api/converter/listing_converter.py",
    "src/business_logic/managers/listing/listing_manager.py",
    ]
timeout = 60.0
excluded-modules = []
test-command = "python -m tests.unit.all_unit_tests"

[cosmic-ray.distributor]
name = "local"
